version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stockpile_django
    ports:
      - "8000:8000"
    volumes:
      # Monte sua pasta local dentro do container
      - ./data:/app/data
    environment:
      # Django não quebra quando rodando atrás de proxy
      - PYTHONUNBUFFERED=1
      - SQLITE_PATH=/app/data/db.sqlite3
    restart: unless-stopped